services:
  wd_actuality.admin.actuality:
    class: WebEtDesign\ActualityBundle\Admin\ActualityAdmin
    arguments: [~, '%wd_actuality.actuality.class%', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Actualilty, label: Actualilty, icon: <i class="fa fa-newspaper-o" aria-hidden="true"></i>, label_translator_strategy: sonata.admin.label.strategy.underscore }
    public: true
    calls:
      - [ setTranslationDomain, [ 'actuality__actuality_admin' ] ]

  wd_actuality.admin.category:
    class: WebEtDesign\ActualityBundle\Admin\CategoryAdmin
    arguments: [~, '%wd_actuality.category.class%', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Actualilty, label: Category, icon: <i class="fa fa-newspaper-o" aria-hidden="true"></i>, label_translator_strategy: sonata.admin.label.strategy.underscore }
    public: true
    calls:
      - [ setTranslationDomain, [ 'actuality__catgeory_admin' ] ]
