services:
  wd_actuality.admin.actuality:
    class: WebEtDesign\ActualityBundle\Admin\ActualityAdmin
    arguments: [~, 'App\Entity\Actuality\Actuality', ~, '%wd_actuality.config%']
    tags:
      - { name: sonata.admin, manager_type: orm, group: Actualilty, label: Actualités, icon: <i class="fa fa-newspaper-o" aria-hidden="true"></i>, label_translator_strategy: sonata.admin.label.strategy.underscore }
    public: true
    calls:
      - [ setTranslationDomain, [ 'actuality__actuality_admin' ] ]

  wd_actuality.admin.category:
    class: WebEtDesign\ActualityBundle\Admin\CategoryAdmin
    arguments: [~, 'App\Entity\Actuality\Category', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Actualilty, label: Catégories, icon: <i class="fa fa-newspaper-o" aria-hidden="true"></i>, label_translator_strategy: sonata.admin.label.strategy.underscore }
    public: true
    calls:
      - [ setTranslationDomain, [ 'actuality__catgeory_admin' ] ]
