services:
  WebEtDesign\ActualityBundle\Repository\:
    resource: '../../Repository/*'
    autowire: true
    tags: ['doctrine.repository_service']

  WebEtDesign\ActualityBundle\Controller\ActualityController:
    autowire: true
    arguments:
      - '%wd_actuality.config%'
    tags: ['controller.service_arguments']
