services:
  WebEtDesign\ActualityBundle\Repository\:
    resource: '../../Repository/*'
    autowire: true
    tags: ['doctrine.repository_service']

  WebEtDesign\ActualityBundle\Controller\ActualityController:
    autowire: true
    arguments:
      - '%wd_actuality.config%'
      - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
      - '@Doctrine\ORM\EntityManagerInterface'
    tags: ['controller.service_arguments']

  WebEtDesign\ActualityBundle\EventListener\SitemapSubscriber:
    autowire: true
    tags:
      - { name: "kernel.event_subscriber", priority: 100 }

  WebEtDesign\ActualityBundle\Maker\MakeActualityBundleSrc:
    autowire: true
    autoconfigure: true
    arguments:
      - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
    tags:
      - 'maker.command'

  WebEtDesign\ActualityBundle\CMS\Page\WDActualitiesPage:
    autowire: true
    autoconfigure: true
    arguments:
      - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'


  WebEtDesign\ActualityBundle\CMS\Page\WDActualityPage:
    autowire: true
    autoconfigure: true
    arguments:
      - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
